name: My First GitHub Actions
on:
  push:
    branches:
          - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v1
   - name: Pipeline Run test
      run:  echo "pipeline run sucessfully"
    #   echo "11111111111111111112222222222222222222222222233333333333333333333333333"
